import type { Metadata } from 'next'
import './globals.css'
import NavbarF from './components/Navbar'

export const metadata: Metadata = {
  title: 'F1-Agile-Portal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <NavbarF/>
        {children}
      </body>
    </html>
  )
}
