package com.f1metag.Pais.Models;

public enum Pais {
    USA("United States of America"),
    AFG("Afghanistan"),
    ALB("Albania"),
    DZA("Algeria"),
    AND("Andorra"),
    AGO("Angola"),
    ATG("Antigua & Deps"),
    ARG("Argentina"),
    ARM("Armenia"),
    AUS("Australia"),
    AUT("Austria"),
    AZE("Azerbaijan"),
    BHS("Bahamas"),
    BHR("Bahrain"),
    BGD("Bangladesh"),
    BRB("Barbados"),
    BLR("Belarus"),
    BEL("Belgium"),
    BLZ("Belize"),
    BEN("Benin"),
    BTN("Bhutan"),
    BOL("Bolivia"),
    BIH("Bosnia Herzegovina"),
    BWA("Botswana"),
    BRA("Brazil"),
    BRN("Brunei"),
    BGR("Bulgaria"),
    BFA("Burkina"),
    BDI("Burundi"),
    KHM("Cambodia"),
    CMR("Cameroon"),
    CAN("Canada"),
    CPV("Cape Verde"),
    TCD("Chad"),
    CHL("Chile"),
    CHN("China"),
    COL("Colombia"),
    COM("Comoros"),
    COD("Democratic Republic of the Congo"),
    COG("Republic of the Congo"),
    CRI("Costa Rica"),
    HRV("Croatia"),
    CUB("Cuba"),
    CYP("Cyprus"),
    CZE("Czech Republic"),
    DNK("Denmark"),
    DJI("Djibouti"),
    DMA("Dominica"),
    DOM("Dominican Republic"),
    TLS("East Timor"),
    ECU("Ecuador"),
    EGY("Egypt"),
    SLV("El Salvador"),
    GNQ("Equatorial Guinea"),
    ERI("Eritrea"),
    EST("Estonia"),
    ETH("Ethiopia"),
    FJI("Fiji"),
    FIN("Finland"),
    FRA("France"),
    GAB("Gabon"),
    GEO("Georgia"),
    DEU("Germany"),
    GHA("Ghana"),
    GRC("Greece"),
    GRD("Grenada"),
    GTM("Guatemala"),
    GIN("Guinea"),
    GNB("Guinea-Bissau"),
    GUY("Guyana"),
    HTI("Haiti"),
    HND("Honduras"),
    HUN("Hungary"),
    ISL("Iceland"),
    IND("India"),
    IDN("Indonesia"),
    IRN("Iran"),
    IRQ("Iraq"),
    IRL("Republic of Ireland"),
    ISR("Israel"),
    ITA("Italy"),
    CIV("Ivory Coast"),
    JAM("Jamaica"),
    JPN("Japan"),
    JOR("Jordan"),
    KAZ("Kazakhstan"),
    KEN("Kenya"),
    KIR("Kiribati"),
    PRK("North Korea"),
    KOR("South Korea"),
    XKX("Kosovo"),
    KWT("Kuwait"),
    KGZ("Kyrgyzstan"),
    LAO("Laos"),
    LVA("Latvia"),
    LBN("Lebanon"),
    LSO("Lesotho"),
    LBR("Liberia"),
    LBY("Libya"),
    LIE("Liechtenstein"),
    LTU("Lithuania"),
    LUX("Luxembourg"),
    MKD("Macedonia"),
    MDG("Madagascar"),
    MWI("Malawi"),
    MYS("Malaysia"),
    MDV("Maldives"),
    MLI("Mali"),
    MLT("Malta"),
    MHL("Marshall Islands"),
    MRT("Mauritania"),
    MUS("Mauritius"),
    MEX("Mexico"),
    FSM("Micronesia"),
    MDA("Moldova"),
    MCO("Monaco"),
    MNG("Mongolia"),
    MNE("Montenegro"),
    MAR("Morocco"),
    MOZ("Mozambique"),
    NAM("Namibia"),
    NRU("Nauru"),
    NPL("Nepal"),
    NLD("Netherlands"),
    NZL("New Zealand"),
    NIC("Nicaragua"),
    NER("Niger"),
    NGA("Nigeria"),
    NOR("Norway"),
    OMN("Oman"),
    PAK("Pakistan"),
    PLW("Palau"),
    PAN("Panama"),
    PNG("Papua New Guinea"),
    PRY("Paraguay"),
    PER("Peru"),
    PHL("Philippines"),
    POL("Poland"),
    PRT("Portugal"),
    QAT("Qatar"),
    ROU("Romania"),
    RUS("Russian Federation"),
    RWA("Rwanda"),
    VCT("Grenadines"),
    WSM("Samoa"),
    SMR("San Marino"),
    STP("Sao Tome & Principe"),
    SAU("Saudi Arabia"),
    SEN("Senegal"),
    SRB("Serbia"),
    SYC("Seychelles"),
    SLE("Sierra Leone"),
    SGP("Singapore"),
    SVK("Slovakia"),
    SVN("Slovenia"),
    SLB("Solomon Islands"),
    SOM("Somalia"),
    ZAF("South Africa"),
    ESP("Spain"),
    LKA("Sri Lanka"),
    SDN("Sudan"),
    SUR("Suriname"),
    SWZ("Swaziland"),
    SWE("Sweden"),
    CHE("Switzerland"),
    SYR("Syria"),
    TJK("Tajikistan"),
    TZA("Tanzania"),
    THA("Thailand"),
    TGO("Togo"),
    TON("Tonga"),
    TTO("Trinidad & Tobago"),
    TUN("Tunisia"),
    TUR("Turkey"),
    TKM("Turkmenistan"),
    TUV("Tuvalu"),
    UGA("Uganda"),
    UKR("Ukraine"),
    ARE("United Arab Emirates"),
    GBR("United Kingdom"),
    URY("Uruguay"),
    UZB("Uzbekistan"),
    VUT("Vanuatu"),
    VAT("Vatican City"),
    VEN("Venezuela"),
    VNM("Vietnam"),
    YEM("Yemen"),
    ZMB("Zambia"),
    ZWE("Zimbabwe");

    private String pais;

    Pais(String country) {
        this.pais = country;
    }

    public String getCode() {
        return this.pais;
    }

}

